# Generated by Django 5.2.8 on 2025-11-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
